# Change these first
owner: Repetiti-Com # Your GitHub organization or username, where this repository lives
repo: repetiti-uptime # The name of this repository

sites:
  - name: Repetiti Main Page
    url: https://www.repetiti.com
  - name: Repetiti Panel
    url: https://panel.repetiti.com
  - name: Repetiti Api
    url: https://news.ycombinator.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.repetiti.com
  # baseUrl: /your-repo-name
  logoUrl: https://panel.repetiti.com/default-symbol-logo.png
  name: Repetiti Uptime Status Page
  introTitle: "Repetiti Uptime Status Page is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: You can see and track uptime of our services.
  navbar:
    - title: Status
      href: /

